# Xcode
# Build, test, and archive an Xcode workspace on macOS.
# Add steps that install certificates, test, sign, and distribute an app, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/xcode

trigger:
  - master
  paths:
    include:
      - ios
    exclude:
      - android

pool:
  vmImage: 'macos-latest'

steps:
  - task: InstallAppleCertificate@2
    inputs:
      certSecureFile: '$(p12FileName)'
      certPwd: '$(p12Password)'
      keychain: 'temp'
      deleteCert: true

  - task: CocoaPods@0
    inputs:
      forceRepoUpdate: false

  - task: Xcode@5
    inputs:
      actions: 'build'
      scheme: 'Runner'
      sdk: 'iphoneos'
      configuration: 'Release'
      xcWorkspacePath: '**/*.xcodeproj/project.xcworkspace'
      xcodeVersion: 'default' # Options: 8, 9, 10, 11, 12, default, specifyPath
      signingOption: "manual"
      teamId: ""
      packageApp: true

  - task: CopyFiles@2
    inputs:
      SourceFolder: "$(Build.SourcesDirectory)/output/package"
      Contents: "**/*.ipa"
      TargetFolder: "$(Build.ArtifactStagingDirectory)"
    displayName: "copy files"

